### ISSUE TITLE
enmap

### ISSUE THREAD

**Issue by DancingPotatoes** [vladdenisov/crove-bot#17]
When i try to `npm install` there is always an error with enmap i tried `npm --force enmap` and still have the same error

this is the error
`Error: Cannot find module 'enmap'
Require stack:
- C:\Users\good\Desktop\crove-bot-mast\index.js`

**Comment by DancingPotatoes** [comment]
and when i try to open the lavalink it says this Error: Unable to access jarfile Lavalink

**Comment by DancingPotatoes** [comment]
I have java 15.0.2 installed. And is it possible to use a host for this bot?

**Comment by vladdenisov** [comment]
Haven't tested bot for a while. Last time I did it, all worked correctly. I've installed it on GCP and AWS.

**Comment by vladdenisov** [comment]
> I have java 15.0.2 installed. And is it possible to use a host for this bot?

As it stated in Lavalink readme, it's better to use Java 13. Other versions may have problems.

**Comment by vladdenisov** [comment]
Could you provide more information about system you're using?

**Comment by DancingPotatoes** [comment]
i am on windows and i am using node v15.11.0.

**Comment by DancingPotatoes** [comment]
i have problems on installing java 13

**Comment by vladdenisov** [comment]
> i am on windows and i am using node v15.11.0.

https://java.tutorials24x7.com/blog/how-to-install-java-13-on-windows

**Comment by vladdenisov** [comment]
> When i try to `npm install` there is always an error with enmap i tried `npm --force enmap` and still have the same error
> 
> this is the error
> `Error: Cannot find module 'enmap'
> Require stack:
> 
> * C:\Users\good\Desktop\crove-bot-mast\index.js`

have you tried installing this?
`npm install --global windows-build-tools`

**Comment by vladdenisov** [comment]
You can also try using version without Lavalink
https://github.com/vladdenisov/crove-bot/releases/tag/v0.2.1

**Comment by DancingPotatoes** [comment]
yea but i realized that i didnt install it when i do its stuck at this
https://prnt.sc/10fzozc

**Comment by DancingPotatoes** [comment]
and i did run it as an administrator

**Comment by DancingPotatoes** [comment]
i cant install enmap too xD

**Comment by DancingPotatoes** [comment]
this is the full error
0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Users\\good\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'i',
0 verbose cli   'enmap'
0 verbose cli ]
1 info using npm@7.6.1
2 info using node@v15.11.0
3 timing config:load:defaults Completed in 2ms
4 timing config:load:file:C:\Users\good\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 3ms
5 timing config:load:builtin Completed in 3ms
6 timing config:load:cli Completed in 2ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:C:\Users\good\Desktop\crove-bot-0.2.1\.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:C:\Users\good\.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:C:\Users\good\AppData\Roaming\npm\etc\npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 1ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 11ms
19 verbose npm-session 719c7340489a159f
20 timing npm:load Completed in 22ms
21 timing arborist:ctor Completed in 1ms
22 timing arborist:ctor Completed in 0ms
23 timing idealTree:init Completed in 15ms
24 timing idealTree:userRequests Completed in 2ms
25 silly idealTree buildDeps
26 silly fetch manifest @logux/eslint-config@^36.1.2
27 http fetch GET 304 https://registry.npmjs.org/@logux%2feslint-config 1062ms (from cache)
28 silly fetch manifest eslint@^6.8.0
29 http fetch GET 304 https://registry.npmjs.org/eslint 124ms (from cache)
30 silly fetch manifest eslint-config-standard@^14.1.1
31 http fetch GET 304 https://registry.npmjs.org/eslint-config-standard 118ms (from cache)
32 silly fetch manifest eslint-plugin-import@^2.20.2
33 http fetch GET 304 https://registry.npmjs.org/eslint-plugin-import 131ms (from cache)
34 silly fetch manifest eslint-plugin-node@^11.1.0
35 http fetch GET 304 https://registry.npmjs.org/eslint-plugin-node 122ms (from cache)
36 silly fetch manifest eslint-plugin-promise@^4.2.1
37 http fetch GET 304 https://registry.npmjs.org/eslint-plugin-promise 120ms (from cache)
38 silly fetch manifest eslint-plugin-standard@^4.0.1
39 http fetch GET 304 https://registry.npmjs.org/eslint-plugin-standard 131ms (from cache)
40 silly fetch manifest eslint-plugin-jest@^23.8.2
41 http fetch GET 304 https://registry.npmjs.org/eslint-plugin-jest 120ms (from cache)
42 silly fetch manifest eslint-plugin-prefer-let@^1.0.1
43 http fetch GET 304 https://registry.npmjs.org/eslint-plugin-prefer-let 125ms (from cache)
44 silly fetch manifest eslint-plugin-security@^1.4.0
45 http fetch GET 304 https://registry.npmjs.org/eslint-plugin-security 119ms (from cache)
46 silly fetch manifest eslint-plugin-unicorn@^18.0.1
47 http fetch GET 304 https://registry.npmjs.org/eslint-plugin-unicorn 132ms (from cache)
48 silly fetch manifest eslint-plugin-unicorn@^19.0.1
49 timing idealTree Completed in 2383ms
50 timing command:i Completed in 2391ms
51 verbose stack Error: unable to resolve dependency tree
51 verbose stack     at Arborist.[failPeerConflict] (C:\Users\good\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1141:25)
51 verbose stack     at Arborist.[loadPeerSet] (C:\Users\good\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1118:34)
51 verbose stack     at async Arborist.[buildDepStep] (C:\Users\good\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:836:11)
51 verbose stack     at async Arborist.buildIdealTree (C:\Users\good\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:209:7)
51 verbose stack     at async Promise.all (index 1)
51 verbose stack     at async Arborist.reify (C:\Users\good\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:130:5)
51 verbose stack     at async Install.install (C:\Users\good\AppData\Roaming\npm\node_modules\npm\lib\install.js:122:5)
52 verbose cwd C:\Users\good\Desktop\crove-bot-0.2.1
53 verbose Windows_NT 10.0.18363
54 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\good\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "enmap"
55 verbose node v15.11.0
56 verbose npm  v7.6.1
57 error code ERESOLVE
58 error ERESOLVE unable to resolve dependency tree
59 error
60 error While resolving: [1m@vladdenisov/crove-bot[22m@[1m0.2.0[22m
60 error Found: [1meslint-plugin-unicorn[22m@[1m18.0.1[22m[2m[22m
60 error [2mnode_modules/eslint-plugin-unicorn[22m
60 error   [33mdev[39m [1meslint-plugin-unicorn[22m@"[1m^18.0.1[22m" from the root project
60 error
60 error Could not resolve dependency:
60 error [35mpeer[39m [1meslint-plugin-unicorn[22m@"[1m^19.0.1[22m" from [1m@logux/eslint-config[22m@[1m36.1.3[22m[2m[22m
60 error [2mnode_modules/@logux/eslint-config[22m
60 error   [33mdev[39m [1m@logux/eslint-config[22m@"[1m^36.1.2[22m" from the root project
60 error
60 error Fix the upstream dependency conflict, or retry
60 error this command with --force, or --legacy-peer-deps
60 error to accept an incorrect (and potentially broken) dependency resolution.
60 error
60 error See C:\Users\good\AppData\Local\npm-cache\eresolve-report.txt for a full report.
61 verbose exit 1

**Comment by vladdenisov** [comment]
Could you also try running this commands in **administrative command prompt or powershell** and then install enmap 
`npm i -g --add-python-to-path --vs2015 --production windows-build-tools`

`npm i -g node-gyp@latest`

**Comment by DancingPotatoes** [comment]
it does the same thing its stuck

**Comment by DancingPotatoes** [comment]
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path C:\Users\good\AppData\Roaming\npm\node_modules\windows-build-tools
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node ./dist/index.js
Downloading python-2.7.15.amd64.msi
npm ERR! [>                                            ] 0.0% (0 B/s)
npm ERR! Downloaded python-2.7.15.amd64.msi. Saved to C:\Users\good\.windows-build-tools\python-2.7.15.amd64.msi.
Downloading BuildTools_Full.exe
npm ERR! [>                                            ] 0.0% (0 B/s)
npm ERR! Downloaded BuildTools_Full.exe. Saved to C:\Users\good\.windows-build-tools\BuildTools_Full.exe.
npm ERR!
npm ERR! Starting installation...
npm ERR! Downloading installers failed. Error: Error: EBUSY: resource busy or locked, unlink 'C:\Users\good\.windows-build-tools\build-tools-log.txt'
npm ERR!     at Object.unlinkSync (node:fs:1264:3)
npm ERR!     at C:\Users\good\AppData\Roaming\npm\node_modules\windows-build-tools\dist\utils\clean.js:13:16
npm ERR!     at Array.forEach (<anonymous>)
npm ERR!     at Object.cleanExistingLogFiles (C:\Users\good\AppData\Roaming\npm\node_modules\windows-build-tools\dist\utils\clean.js:11:11)
npm ERR!     at Object.install (C:\Users\good\AppData\Roaming\npm\node_modules\windows-build-tools\dist\install\index.js:28:13)
npm ERR!     at C:\Users\good\AppData\Roaming\npm\node_modules\windows-build-tools\dist\start.js:17:19
npm ERR!     at Object.download (C:\Users\good\AppData\Roaming\npm\node_modules\windows-build-tools\dist\download.js:35:5)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:94:5)
npm ERR!     at async Object.aquireInstallers (C:\Users\good\AppData\Roaming\npm\node_modules\windows-build-tools\dist\aquire-installers.js:32:13) {
npm ERR!   errno: -4082,
npm ERR!   syscall: 'unlink',
npm ERR!   code: 'EBUSY',
npm ERR!   path: 'C:\\Users\\good\\.windows-build-tools\\build-tools-log.txt'
npm ERR! }
npm ERR! windows-build-tools will now exit.

npm ERR! A complete log of this run can be found in:

**Comment by DancingPotatoes** [comment]
i installed the second one with no problem which is `npm i -g node-gyp@latest` but the other one i cant

**Comment by DancingPotatoes** [comment]
i was now able to fix my problems with the installing when i installed the one without the java i got a new error when i try to run the bot `node .`
It gives me this err 
throw new TypeError('CLIENT_MISSING_INTENTS');
      ^

TypeError [CLIENT_MISSING_INTENTS]: Valid intents must be provided for the Client.

**Comment by vladdenisov** [comment]
> i was now able to fix my problems with the installing when i installed the one without the java i got a new error when i try to run the bot `node .`
> It gives me this err
> throw new TypeError('CLIENT_MISSING_INTENTS');
> ^
> 
> TypeError [CLIENT_MISSING_INTENTS]: Valid intents must be provided for the Client.

I faced this error too, but i can't fix this right now. I really don't know why it doesn't work :/

**Comment by vladdenisov** [comment]
If you want, you can open new issue about this problem. I will close this for now.

> i was now able to fix my problems with the installing when i installed the one without the java i got a new error when i try to run the bot `node .`
> It gives me this err
> throw new TypeError('CLIENT_MISSING_INTENTS');
> ^
> 
> TypeError [CLIENT_MISSING_INTENTS]: Valid intents must be provided for the Client.
